[2024-11-29T00:34:12.421+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-29T00:34:12.450+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipe.get_token scheduled__2024-11-28T00:00:00+00:00 [queued]>
[2024-11-29T00:34:12.461+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipe.get_token scheduled__2024-11-28T00:00:00+00:00 [queued]>
[2024-11-29T00:34:12.462+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-11-29T00:34:12.478+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): get_token> on 2024-11-28 00:00:00+00:00
[2024-11-29T00:34:12.488+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1078) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-29T00:34:12.490+0000] {standard_task_runner.py:72} INFO - Started process 1079 to run task
[2024-11-29T00:34:12.494+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pipe', 'get_token', 'scheduled__2024-11-28T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmp8ag2gmms']
[2024-11-29T00:34:12.496+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask get_token
[2024-11-29T00:34:12.570+0000] {task_command.py:467} INFO - Running <TaskInstance: pipe.get_token scheduled__2024-11-28T00:00:00+00:00 [running]> on host 6bcbc17aec1f
[2024-11-29T00:34:12.677+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pipe' AIRFLOW_CTX_TASK_ID='get_token' AIRFLOW_CTX_EXECUTION_DATE='2024-11-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-28T00:00:00+00:00'
[2024-11-29T00:34:12.678+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-29T00:34:13.127+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-29T00:34:13.142+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-29T00:34:13.143+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=pipe, task_id=get_token, run_id=scheduled__2024-11-28T00:00:00+00:00, execution_date=20241128T000000, start_date=20241129T003412, end_date=20241129T003413
[2024-11-29T00:34:13.188+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-29T00:34:13.236+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-29T00:34:13.239+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-11-29T01:13:02.317+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-29T01:13:02.349+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipe.get_token scheduled__2024-11-28T00:00:00+00:00 [queued]>
[2024-11-29T01:13:02.365+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipe.get_token scheduled__2024-11-28T00:00:00+00:00 [queued]>
[2024-11-29T01:13:02.366+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-11-29T01:13:02.390+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): get_token> on 2024-11-28 00:00:00+00:00
[2024-11-29T01:13:02.402+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=77) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-29T01:13:02.404+0000] {standard_task_runner.py:72} INFO - Started process 80 to run task
[2024-11-29T01:13:02.405+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pipe', 'get_token', 'scheduled__2024-11-28T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpyeoafpgx']
[2024-11-29T01:13:02.407+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask get_token
[2024-11-29T01:13:02.484+0000] {task_command.py:467} INFO - Running <TaskInstance: pipe.get_token scheduled__2024-11-28T00:00:00+00:00 [running]> on host 768115ef6318
[2024-11-29T01:13:02.628+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pipe' AIRFLOW_CTX_TASK_ID='get_token' AIRFLOW_CTX_EXECUTION_DATE='2024-11-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-28T00:00:00+00:00'
[2024-11-29T01:13:02.629+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-29T01:13:02.646+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/pipeline.py", line 21, in get_token
    client_id = Variable.get("client_id")
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable client_id does not exist'
[2024-11-29T01:13:02.665+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=pipe, task_id=get_token, run_id=scheduled__2024-11-28T00:00:00+00:00, execution_date=20241128T000000, start_date=20241129T011302, end_date=20241129T011302
[2024-11-29T01:13:02.685+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-29T01:13:02.685+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 4 for task get_token ('Variable client_id does not exist'; 80)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/pipeline.py", line 21, in get_token
    client_id = Variable.get("client_id")
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable client_id does not exist'
[2024-11-29T01:13:02.741+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-29T01:13:02.784+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-29T01:13:02.790+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-11-29T02:26:03.975+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-29T02:26:04.000+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipe.get_token scheduled__2024-11-28T00:00:00+00:00 [queued]>
[2024-11-29T02:26:04.009+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipe.get_token scheduled__2024-11-28T00:00:00+00:00 [queued]>
[2024-11-29T02:26:04.009+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-11-29T02:26:04.026+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): get_token> on 2024-11-28 00:00:00+00:00
[2024-11-29T02:26:04.038+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1131) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-29T02:26:04.040+0000] {standard_task_runner.py:72} INFO - Started process 1132 to run task
[2024-11-29T02:26:04.044+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pipe', 'get_token', 'scheduled__2024-11-28T00:00:00+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmps3rv6_j5']
[2024-11-29T02:26:04.046+0000] {standard_task_runner.py:105} INFO - Job 44: Subtask get_token
[2024-11-29T02:26:04.120+0000] {task_command.py:467} INFO - Running <TaskInstance: pipe.get_token scheduled__2024-11-28T00:00:00+00:00 [running]> on host 768115ef6318
[2024-11-29T02:26:04.245+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pipe' AIRFLOW_CTX_TASK_ID='get_token' AIRFLOW_CTX_EXECUTION_DATE='2024-11-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-28T00:00:00+00:00'
[2024-11-29T02:26:04.246+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-29T02:26:04.752+0000] {logging_mixin.py:190} INFO - BQBODL505LImKaqXTIz8cjcp1Qejbu0aU5df7HB8FlObNhXRxw1jJReLrvJ2mNEiCCX4h9u4eI_dlOwwKzlMnqOnI1-wcw03PL-fxvTK7QUmJ-rLg08
[2024-11-29T02:26:04.754+0000] {python.py:240} INFO - Done. Returned value was: BQBODL505LImKaqXTIz8cjcp1Qejbu0aU5df7HB8FlObNhXRxw1jJReLrvJ2mNEiCCX4h9u4eI_dlOwwKzlMnqOnI1-wcw03PL-fxvTK7QUmJ-rLg08
[2024-11-29T02:26:04.790+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-29T02:26:04.791+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=pipe, task_id=get_token, run_id=scheduled__2024-11-28T00:00:00+00:00, execution_date=20241128T000000, start_date=20241129T022604, end_date=20241129T022604
[2024-11-29T02:26:04.857+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-29T02:26:04.897+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-29T02:26:04.898+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
